config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"

    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/table", to: "static_pages#table"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale &action
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def table; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = t "base_title"
    page_title.blank? ? base_title : page_title + " | " + base_title
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".help"), help_path %></li>
      <li><%= link_to t(".news"), Settings.links.rails_tutorial.home_page %></li>
      <li><%= link_to t(".en"), locale: :en %></li>
      <li><%= link_to t(".vi"), locale: :vi %></li>
      <li> © 2020 Copyright</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".logo_alt"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <li><%= link_to t(".table"), table_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, (t ".title") %>
<h1><%= t ".heading" %></h1>
<p>
  <%= t ".detail" %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".heading" %></h1>
<p>
  <%= t ".description" %>
</p>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".hello" %></h1>
<%= link_to t(".ruby"), Settings.links.rails_tutorial.home_page %>

app/views/static_pages/table.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".heading" %></h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>